'use strict';
const express=require('express');
const {authMiddleware,prisma}=require('../middleware');
const service=require('../services/scanTransfers');
const stocktakeTransfers=require('../services/stocktakeTransfers');
const actions=require('../services/scanActionTransfers');
const router=express.Router();
router.use(authMiddleware);
router.use(async(req,res,next)=>{try{req.transferActor=await service.operator(prisma,req.userId);next();}catch(e){res.status(e.status||500).json({error:e.status?e.message:'Não foi possível verificar seu acesso.'});}});
function handle(fn){return async(req,res)=>{try{res.set('Cache-Control','no-store');res.json(await fn(req));}catch(e){res.status(e.status||500).json({error:e.status?e.message:'Não foi possível concluir. Atualize e tente novamente com a mesma leitura.'});}};}
router.get('/me',handle(async r=>({user:r.transferActor})));
router.get('/actions/context',handle(r=>actions.context(prisma,r.transferActor)));
router.post('/actions/lookup',handle(r=>actions.lookup(prisma,r.transferActor,r.body||{})));
router.post('/actions/send-preview',handle(r=>actions.sendPreview(prisma,r.transferActor,r.body||{})));
router.post('/actions/send-confirm',handle(r=>actions.sendConfirm(prisma,r.transferActor,r.body||{})));
router.get('/actions/pending',handle(r=>actions.pending(prisma,r.transferActor,{storeId:String(r.query.storeId||'')})));
router.post('/actions/:id/receive-preview',handle(r=>actions.receivePreview(prisma,r.transferActor,r.params.id,r.body||{})));
router.post('/actions/:id/receive-confirm',handle(r=>actions.receiveConfirm(prisma,r.transferActor,r.params.id,r.body||{})));
router.post('/lookup',handle(r=>service.lookup(prisma,r.transferActor,r.body||{})));
router.post('/confirm',handle(r=>service.transfer(prisma,r.transferActor,r.body||{})));
router.post('/batch-preview',handle(r=>stocktakeTransfers.preview(prisma,r.transferActor,r.body||{})));
router.post('/batch-confirm',handle(r=>stocktakeTransfers.confirm(prisma,r.transferActor,r.body||{})));
router.post('/:id/undo',handle(r=>service.undo(prisma,r.transferActor,r.params.id)));
router.get('/history',handle(r=>service.history(prisma,r.transferActor,String(r.query.sessionId||''))));
module.exports=router;
